### ISSUE TITLE
Fire pit spams console

### ISSUE THREAD

**Issue by justinrusso** [TheTurkeyDev/Progression-Tweaks#1]
Reference: https://github.com/Darkosto/SevTech-Ages/issues/605 and https://github.com/Darkosto/SevTech-Ages/issues/681

**Comment by sarcastic6** [comment]
Perhaps:
https://github.com/Turkey2349/Progression-Tweaks/blob/ad51f0bb9a78b60dc890a2e9be582fb9e6e1afbe/src/main/java/com/theprogrammingturkey/progressiontweaks/blocks/tileentities/TileFirePit.java#L239
and:
https://github.com/Turkey2349/Progression-Tweaks/blob/ad51f0bb9a78b60dc890a2e9be582fb9e6e1afbe/src/main/java/com/theprogrammingturkey/progressiontweaks/blocks/tileentities/TileFirePit.java#L249

**Comment by TheTurkeyDev** [comment]
Fixed
